version: '3.8'

services:
  # --- SERVICE 1: The Initializer ---
#  ledger-init:
#    image: ethereum/client-go:v1.13.15
#    container_name: family-ledger-init
#    # We mount the local folder where Coolify stores persistent data
#    volumes:
#      - ledger-data:/root/.ethereum
#      - ./genesis.json:/root/genesis.json
#    # No shell needed; we call the geth binary directly to init the genesis
#    command:
#      - init
#      - --datadir=/root/.ethereum
#      - /root/genesis.json
#    restart: "no" # This container runs, does its job, and stops.

#  ledger-import:
#    image: ethereum/client-go:v1.13.15
#    container_name: family-ledger-import
#    depends_on:
#      ledger-init:
#        condition: service_started
#    volumes:
#      - ledger-data:/root/.ethereum
#      - ./pkey.txt:/root/pkey.txt:ro
#      - ./password.txt:/root/password.txt:ro
#    # This command imports the key and encrypts it into the keystore
#    command:
#      - account
#      - import
#      - --datadir=/root/.ethereum
#      - --password=/root/password.txt
#      - /root/pkey.txt
#    restart: "no"

  # --- SERVICE 2: The Actual Node ---
  ledger-node:
    image: ethereum/client-go:v1.13.15
    container_name: family-ledger
    restart: always
    # This tells Coolify to start the init container first
#    depends_on:
#      ledger-import:
#        condition: service_completed_successfully # Waits for the key to be imported
    ports:
      - "8545:8545"   # RPC for MetaMask
      - "30303:30303" # P2P Connection
    volumes:
      - ledger-data:/root/.ethereum
      - ./password.txt:/root/password.txt
    command:
      - --datadir=/root/.ethereum
      - --networkid=27744
      - --mine
      - --miner.gasprice=0
      - --miner.etherbase=0x0aca0b79de83a0761a5c57c8a1a239989cd254a6
      - --unlock=0x0aca0b79de83a0761a5c57c8a1a239989cd254a6
      - --password=/root/password.txt
      - --allow-insecure-unlock
      - --http
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.api=eth,net,web3,clique,miner,debug,txpool

  explorer:
    image: otterscan/otterscan:v2.11.0
    container_name: family-explorer
    restart: always
    ports:
      - "3094:80"
    # Otterscan works by the browser talking to the node.
    # This environment variable tells the browser where the node is.
    environment:
      - ERIGON_URL=http://ledger-node:8545

volumes:
  ledger-data:
