[Eth]
NetworkId = 27744
SyncMode = "full"
NoMining = false # Must be false to allow "sealing" blocks

[Node]
DataDir = "/root/.ethereum"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "clique", "miner"]

[Miner]
GasPrice = 0
Etherbase = "0x0aCa0B79de83a0761a5c57c8a1A239989cD254A6"